# Generated by Django 5.2.7 on 2025-10-26 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الكاميرا')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('camera_type', models.CharField(choices=[('cctv', 'CCTV'), ('traffic', 'Traffic Camera'), ('thermal', 'Thermal Camera'), ('dome', 'Dome Camera'), ('ptz', 'PTZ Camera')], default='cctv', max_length=20, verbose_name='نوع الكاميرا')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Under Maintenance')], default='online', max_length=20, verbose_name='الحالة')),
                ('rtsp_url', models.URLField(blank=True, null=True, verbose_name='رابط RTSP')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'كاميرا',
                'verbose_name_plural': 'الكاميرات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('accident', 'حادث مروري'), ('congestion', 'ازدحام مروري'), ('suspicious', 'نشاط مشبوه'), ('violence', 'عنيف/شجار'), ('fire', 'حريق'), ('crowd', 'تجمع غير طبيعي'), ('object', 'جسم مشبوه'), ('vandalism', 'تخريب'), ('theft', 'سرقة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الحادث')),
                ('confidence', models.FloatField(verbose_name='مستوى الثقة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='الوقت')),
                ('frame_data', models.TextField(blank=True, verbose_name='بيانات الإطار')),
                ('bounding_boxes', models.JSONField(blank=True, null=True, verbose_name='مربعات الاكتشاف')),
                ('description', models.TextField(blank=True, verbose_name='وصف الحادث')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('is_false_alarm', models.BooleanField(default=False, verbose_name='إنذار خاطئ')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.camera', verbose_name='الكاميرا')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة')),
            ],
            options={
                'verbose_name': 'كشف حادث',
                'verbose_name_plural': 'كشف الحوادث',
                'ordering': ['-timestamp'],
            },
        ),
    ]
