# Generated by Django 5.2.7 on 2025-10-26 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('sound_type', models.CharField(choices=[('scream', 'صراخ'), ('gunshot', 'طلقة نار'), ('explosion', 'انفجار'), ('crash', 'اصطدام/حادث'), ('siren', 'صافرة إنذار'), ('glass_break', 'كسر زجاج'), ('alarm', 'صوت إنذار'), ('fighting', 'شجار'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الصوت')),
                ('confidence', models.FloatField(verbose_name='مستوى الثقة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='الوقت')),
                ('audio_file', models.FileField(upload_to='audio_detections/%Y/%m/%d/', verbose_name='ملف الصوت')),
                ('duration', models.FloatField(default=0, verbose_name='المدة (بالثواني)')),
                ('decibel_level', models.FloatField(blank=True, null=True, verbose_name='مستوى الديسيبل')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة')),
            ],
            options={
                'verbose_name': 'كشف صوتي',
                'verbose_name_plural': 'الكشف الصوتي',
                'ordering': ['-timestamp'],
            },
        ),
    ]
