# Generated by Django 5.2.7 on 2025-10-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(verbose_name='نص البلاغ')),
                ('report_type', models.CharField(choices=[('crime', 'بلاغ جريمة'), ('accident', 'بلاغ حادث'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح'), ('emergency', 'طوارئ'), ('traffic', 'مرور'), ('other', 'أخرى')], max_length=20, verbose_name='نوع البلاغ')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('urgency_level', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='مستوى الاستعجال')),
                ('confidence', models.FloatField(default=0.0, verbose_name='مستوى الثقة')),
                ('processed_text', models.TextField(blank=True, verbose_name='النص المعالج')),
                ('entities', models.JSONField(blank=True, null=True, verbose_name='الكيانات المستخرجة')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تم المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم المعالجة بواسطة')),
            ],
            options={
                'verbose_name': 'بلاغ مواطن',
                'verbose_name_plural': 'بلاغات المواطنين',
                'ordering': ['-created_at'],
            },
        ),
    ]
